# Site settings
title: HillCyber
email: info@hillcyber.com
url: https://HillCyber.github.io
description: "As rapidly evolving cyber threats spread online, our network-level technology protects your digital assets. By monitoring activity, we provide full coverage of networks, computers and Internet of Things (IoT) devices, closing security gaps that can expose your data. Our training and data solutions ensure that your networks as well as the people who depend on them are resilient. Dramatically improve your organization’s security without the drama."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: HillCyber

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
