---
title: HillCyber
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@hillcyber.com
url: https://HillCyber.com
description:
  Advanced Cyber - Network Assurance - Data Security <br/>
  <strong> FOR EVERY NETWORK, FOR EVERY ORGANIZATION, FOR EVERYONE </strong>
color:
  primary-dark: "#000000"
  links: "#219ab3"
footer: HillCyber
social:
- title: twitter
  url: https://twitter.com/TheHillCyber
- title: facebook
  url: https://www.facebook.com/HillCyber-234443477017662/
markdown: kramdown
permalink: pretty
