---
title: HillCyber
timezone: "America/New_York"
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@hillcyber.com
url: https://HillCyber.com
ceo: Jon Steinman
ceo_linkedin: https://www.linkedin.com/in/jcsteinman
cto: Matt Webster
cto_linkedin: https://www.linkedin.com/in/mattwebster
description:
  Advanced Cyber * IT Infrastructure * Operations & Security
  <flag> MILITARY-GRADE CYBER FOR EVERY NETWORK, FOR EVERY ORGANIZATION, FOR EVERYONE </flag>
description-beta:
  Advanced Cyber - IT Infrastructure - Physical Security <br/><br/>
  <flag>
    Unified IT Cybersecurity Platform <br/>
    Successfully Tested at the Pentagon’s Advanced Research Agency <br/>
    Scalable for Every Organization <br/>
  </flag>
color:
  primary-dark: "#000000"
  links: "#219ab3"
footer: HillCyber
social:
- title: twitter
  url: https://twitter.com/TheHillCyber
- title: facebook
  url: https://www.facebook.com/HillCyber-234443477017662/
markdown: kramdown
permalink: pretty
